"""Connect a toy environment to an agent rollout and build token-aligned data."""

TASK = {
    "title": "Agent Environment Adapter",
    "difficulty": "Medium",
    "version": 1,
    "function_name": "agent_env_adapter",
    "description_en": r"""Run an agent in an environment and return a token-aligned trajectory.

**Signature:** `agent_env_adapter(env, policy, max_steps) -> dict`

The environment has `reset() -> observation` and
`step(action) -> (observation, reward, terminated, truncated, info)`.
`policy(observation)` returns a dictionary with `token_ids` (a list of
integers produced by the model) and `action`. At each step call the policy
once, then call the environment once. Return exactly these keys:
`response_ids`, `response_mask`, `rewards`, `return`, `terminated`,
and `truncated`. Concatenate policy token ids; the mask is one for every
policy token. Environment observations are context and must not appear in the
response mask. Stop on either end flag or after `max_steps`; a budget stop
sets both end flags to false.

────────────────

**Background — context only.** This is the environment seam in an agentic RL
system. VERL's AgentLoop and Slime's custom generate function may add tools,
chat templates, and async servers around it, but the trainer still needs an
aligned policy-token sequence and a scalar trajectory reward. Marking
environment output as trainable teaches the model to imitate the environment
instead of its own actions.""",
    "advisory_prerequisites": ["agentic_rollout_loop", "response_token_mask"],
    "hints": [
        {"level": 1, "kind": "questions", "content": "Which tokens were generated by the policy, and which values came from the environment? What must stay aligned when several turns have different token counts? Which end flag wins when the step budget is exhausted?"},
        {"level": 2, "kind": "analysis", "content": "Keep one response_ids list and append policy token_ids after every policy call. Append the same number of True entries to response_mask; do not tokenize or mask observations. Accumulate each reward, stop immediately on terminated or truncated, and report the final flags plus the sum of rewards."},
    ],
    "model_connections": [
        "VERL's AgentLoopOutput carries response ids, a response mask, and reward after tools or environments finish.",
        "Slime's custom generate hook is the analogous place to call an environment before converting the sample for training.",
    ],
    "sources": [{
        "kind": "code",
        "url": "https://github.com/verl-project/verl",
        "commit": "12ebe0cb4d300c58449fb6c675379e8700015c51",
        "path": "verl/experimental/agent_loop/agent_loop.py",
        "symbol": "AgentLoopOutput",
        "license": "Apache-2.0",
        "adapted": "The adapter exposes policy-generated tokens and a response mask at the environment boundary.",
        "simplifications": "Uses a synchronous toy environment and omits server requests, chat templates, tool parsing, and padding."
    }],
    "tests": [
        {"name": "Builds aligned policy-token trajectory", "behavior": "rl.rollout_assembly", "code": r"""
class Env:
    def __init__(self): self.n = 0
    def reset(self): return "start"
    def step(self, action):
        self.n += 1
        return ("obs" + str(self.n), 0.5, self.n == 2, False, {})
def policy(obs):
    return {"token_ids": [len(obs), 9], "action": "go"}
out = {fn}(Env(), policy, 5)
assert out["response_ids"] == [5, 9, 4, 9]
assert out["response_mask"] == [True, True, True, True]
assert out["rewards"] == [0.5, 0.5]
assert out["return"] == 1.0 and out["terminated"] is True and out["truncated"] is False
"""},
        {"name": "Stops on truncation and preserves partial data", "visibility": "unshown", "behavior": "budget.enforcement", "failure_message": "The adapter stepped after truncation or lost the tokens and reward already collected.", "code": r"""
class Env:
    def __init__(self): self.steps = 0
    def reset(self): return 0
    def step(self, action):
        self.steps += 1
        return self.steps, 2.0, False, True, {}
def policy(obs): return {"token_ids": [obs], "action": obs}
env = Env(); out = {fn}(env, policy, 10)
assert env.steps == 1
assert out["response_ids"] == [0] and out["response_mask"] == [True]
assert out["rewards"] == [2.0] and out["return"] == 2.0
assert out["terminated"] is False and out["truncated"] is True
"""},
        {"name": "Seeded variable-length actions match an independent trajectory", "visibility": "unshown", "behavior": "rl.rollout_assembly", "failure_message": "Policy token lengths, rewards, and end flags must remain aligned across turns.", "code": r"""
import random
for seed in (11, 23, 37):
    rng = random.Random(seed)
    token_groups = [[rng.randrange(100) for _ in range(rng.randrange(1, 4))] for _ in range(4)]
    rewards = [rng.randint(-3, 4) for _ in range(4)]
    final_step = rng.randrange(1, 5)
    is_truncated = bool(seed % 2)
    class Env:
        def __init__(self): self.index=0
        def reset(self): return 0
        def step(self, action):
            assert action == self.index
            reward = rewards[self.index]
            self.index += 1
            done = self.index == final_step
            return self.index, reward, done and not is_truncated, done and is_truncated, {}
    env=Env()
    got={fn}(env, lambda obs: {"token_ids": token_groups[obs], "action": obs}, 4)
    expected_ids = [token for group in token_groups[:final_step] for token in group]
    assert got == {
        "response_ids": expected_ids, "response_mask": [True] * len(expected_ids),
        "rewards": [float(r) for r in rewards[:final_step]],
        "return": float(sum(rewards[:final_step])),
        "terminated": not is_truncated, "truncated": is_truncated,
    }, (seed, got)
    assert env.index == final_step
"""},
        {"name": "A step budget is not an environment termination", "visibility": "unshown", "behavior": "state.invariant", "failure_message": "Exhausting max_steps must stop collection without inventing terminated or truncated.", "code": r"""
class Env:
    def reset(self): return 0
    def step(self, action): return 0, 1.0, False, False, {}
out = {fn}(Env(), lambda obs: {"token_ids": [1, 2], "action": 0}, 2)
assert len(out["rewards"]) == 2
assert out["terminated"] is False and out["truncated"] is False
"""},
        {"name": "Rejects an invalid step budget", "visibility": "unshown", "behavior": "contract.signature", "failure_message": "The adapter accepted a zero or negative max_steps.", "code": r"""
try: {fn}(None, None, 0)
except ValueError: pass
else: raise AssertionError("max_steps must be positive")
"""},
    ],
    "solution": '''def agent_env_adapter(env, policy, max_steps):
    if not isinstance(max_steps, int) or isinstance(max_steps, bool) or max_steps <= 0:
        raise ValueError("max_steps must be a positive integer")
    observation = env.reset()
    response_ids, response_mask, rewards = [], [], []
    terminated = truncated = False
    for _ in range(max_steps):
        output = policy(observation)
        token_ids = list(output["token_ids"])
        response_ids.extend(token_ids)
        response_mask.extend([True] * len(token_ids))
        observation, reward, terminated, truncated, _ = env.step(output["action"])
        rewards.append(float(reward))
        if terminated or truncated:
            break
    return {
        "response_ids": response_ids,
        "response_mask": response_mask,
        "rewards": rewards,
        "return": sum(rewards),
        "terminated": bool(terminated),
        "truncated": bool(truncated),
    }
''',
}
