"""Agent rollout truncation — preserve aligned trajectory metadata at the context boundary."""

TASK = {
    "title": "Agent Rollout Truncation",
    "difficulty": "Hard",
    "version": 1,
    "function_name": "finalize_agent_rollout",
    "description_en": r"""Finalize one tokenized multi-turn rollout when its response may have crossed the training window.

**Signature:** `finalize_agent_rollout(response_ids, response_mask, rollout_log_probs, reward, max_response_length, overlong_penalty) -> dict`

**Parameters:**
- `response_ids` — one-dimensional integer tensor containing assistant and tool-response tokens in trajectory order.
- `response_mask` — one-dimensional boolean tensor with the same length. True marks a token generated by the policy; False marks tool output.
- `rollout_log_probs` — one-dimensional floating-point tensor with one rollout-time log-probability per response position. Tool positions may contain zero.
- `reward` — the scalar trajectory reward before any length penalty.
- `max_response_length` — positive integer width available to the response in the training batch.
- `overlong_penalty` — non-negative scalar penalty subtracted from `reward` only when the original trajectory is longer than `max_response_length`.

**Returns:** a dictionary with exactly five keys:
- `response_ids` — a cloned prefix of at most `max_response_length` tokens.
- `response_mask` — the matching cloned prefix of the policy mask.
- `rollout_log_probs` — the matching cloned prefix of rollout log-probabilities.
- `token_rewards` — a floating-point tensor matching the retained response. It is zero except at the final retained position, which holds `reward - overlong_penalty` for an overlong trajectory and `reward` otherwise.
- `truncated` — a Python boolean which is True exactly when the original length was greater than `max_response_length`.

**Constraints:**
- Keep the oldest prefix. Never keep the newest suffix: later tokens depend on context that would then be missing.
- Slice token ids, policy mask and rollout log-probabilities at the same boundary.
- A trajectory whose length equals the limit fits exactly and is not penalized.
- Put the scalar reward on the final retained response position even when that position is tool output. Reward aggregation sums over the trajectory first; the policy mask is applied later when the scalar advantage is broadcast to policy-generated tokens.
- Return clones, not views into the caller's tensors.
- Raise `ValueError` unless all three tensors are one-dimensional, non-empty, on the same device and have the same length; unless `response_ids` is integer, `response_mask` is boolean and `rollout_log_probs` is floating point; unless `max_response_length` is a positive integer; and unless `overlong_penalty` is non-negative.

────────────────────────────────

**Background — context only. Everything above this line is the requirement.**

**Why overflow is decided before slicing.** Once all aligned tensors have width `max_response_length`, an exact-fit rollout and an overlong rollout have the same shape. The original length is the only reliable signal for applying the penalty and reporting truncation.

**Why prefix truncation is coherent.** Every token in an autoregressive trajectory depends on the tokens before it. Keeping a suffix discards causal context while pretending the retained log-probabilities still describe the visible sequence.

**Why reward and trainability use different positions.** A tool response can exhaust the remaining window. verl records outcome reward at the last real response position, then its GRPO estimator sums that reward into one trajectory score and broadcasts the resulting advantage only across positions selected by `response_mask`. Moving reward backward to the last assistant token mixes those two stages and breaks other estimators that care about timing.

**The hidden failure mode is misalignment.** Truncating only tokens, or taking different slices of the mask and rollout log-probabilities, produces tensors with plausible shapes but attributes a policy decision and its probability to the wrong token. That corrupts importance ratios without necessarily producing an exception.""",
    "advisory_prerequisites": [
        "response_token_mask",
        "group_relative_advantage",
        "rollout_batch_assembly",
        "agentic_rollout_loop",
    ],
    "hints": [
        {
            "level": 1,
            "kind": "questions",
            "content": "Which fact disappears after you slice every tensor to the window width? Save that fact first. Then choose the causal side of the trajectory to retain: can a suffix be interpreted without the prefix it attended to? Keep the three aligned arrays together. Finally separate reward storage from gradient selection: if the last retained position is tool output, where does the scalar trajectory reward live, and which tensor later prevents that tool token from receiving policy gradient?",
        },
        {
            "level": 2,
            "kind": "analysis",
            "content": "Validate shape, length, dtype and device before doing any work. Record `original_length = response_ids.numel()` and define truncation with a strict greater-than comparison. Let `kept = min(original_length, max_response_length)`, then clone `[:kept]` from all three aligned tensors. Compute the effective reward by subtracting the penalty only when `truncated` is true. Allocate `token_rewards` with `zeros_like` on the retained floating-point log-probabilities and assign the effective reward to index `-1`. Do not search the policy mask for that position: the reward belongs to the whole trajectory, while the mask independently controls which tokens receive its later advantage.",
        },
    ],
    "model_connections": [
        "verl's ToolAgentLoop stops after the aligned response mask reaches the configured response length and returns the same prefix slice for response ids, policy mask and rollout log-probabilities.",
        "verl's AgentLoopManager pads the retained response and keeps response_mask separate from the attention mask because tool tokens are real context but are not policy actions.",
        "verl's GRPO estimator sums token rewards into one trajectory score, normalizes that score within its prompt group, then multiplies the scalar advantage by response_mask.",
        "The existing agentic_rollout_loop exercise stops at a turn budget; this exercise handles the different boundary where tokenized assistant and tool turns exhaust the model window.",
    ],
    "pro_con_analysis": {
        "pros": [
            "Prefix truncation preserves a causally valid sequence and keeps every per-token field aligned.",
            "A separate truncation flag makes length penalties and overflow metrics explicit after shapes have been normalized.",
            "Keeping reward placement separate from the policy mask supports both outcome estimators and token-aware estimators.",
        ],
        "cons": [
            "Hard right truncation may discard the answer or terminal tool result that determines whether the trajectory actually succeeded.",
            "A fixed penalty treats an overflow by one token the same as a much longer runaway trajectory.",
            "The retained prefix may end inside a tool response or assistant turn; production systems often add turn-aware stopping before this final safety cap.",
        ],
    },
    "sources": [
        {
            "kind": "code",
            "url": "https://github.com/volcengine/verl",
            "commit": "12ebe0cb4d300c58449fb6c675379e8700015c51",
            "path": "verl/experimental/agent_loop/tool_agent_loop.py",
            "symbol": "ToolAgentLoop.run, ToolAgentLoop._handle_generating_state, ToolAgentLoop._handle_processing_tools_state",
            "license": "Apache-2.0",
            "adapted": "The response-length termination checks and the shared prefix cap applied to response ids, response_mask and response_logprobs.",
            "simplifications": "Collapses the asynchronous state machine, continuous-token builder, tools and multimodal data into already aligned one-dimensional tensors.",
        },
        {
            "kind": "code",
            "url": "https://github.com/volcengine/verl",
            "commit": "12ebe0cb4d300c58449fb6c675379e8700015c51",
            "path": "verl/experimental/agent_loop/agent_loop.py",
            "symbol": "AgentLoopOutput.as_dict, AgentLoopManager._agent_loop_postprocess, AgentLoopManager._postprocess",
            "license": "Apache-2.0",
            "adapted": "The aligned response metadata contract, terminal reward placement and distinction between attention_mask and response_mask.",
            "simplifications": "Omits prompt padding, position ids, routed experts, multimodal inputs and batch concatenation.",
        },
        {
            "kind": "code",
            "url": "https://github.com/volcengine/verl",
            "commit": "12ebe0cb4d300c58449fb6c675379e8700015c51",
            "path": "verl/trainer/ppo/core_algos.py",
            "symbol": "compute_grpo_outcome_advantage",
            "license": "Apache-2.0",
            "adapted": "The separation between summing token rewards into a trajectory score and broadcasting its scalar advantage only over response_mask positions.",
            "simplifications": "Does not perform group normalization or advantage estimation; it prepares the aligned reward and mask inputs those stages consume.",
        },
        {
            "kind": "paper",
            "url": "https://arxiv.org/abs/2503.14476",
            "section": "3.4 Overlong Reward Shaping",
        },
    ],
    "tests": [
        {
            "name": "Overflow keeps one aligned prefix and applies the penalty",
            "behavior": "rl.trajectory",
            "code": r"""
import torch
ids = torch.tensor([10, 11, 20, 21, 12, 13])
mask = torch.tensor([True, True, False, False, True, True])
log_probs = torch.tensor([-0.1, -0.2, 0.0, 0.0, -0.3, -0.4])
out = {fn}(ids, mask, log_probs, reward=2.0, max_response_length=4, overlong_penalty=0.75)
assert set(out) == {'response_ids', 'response_mask', 'rollout_log_probs', 'token_rewards', 'truncated'}, sorted(out)
assert out['truncated'] is True
assert torch.equal(out['response_ids'], torch.tensor([10, 11, 20, 21])), out['response_ids']
assert torch.equal(out['response_mask'], torch.tensor([True, True, False, False])), out['response_mask']
assert torch.allclose(out['rollout_log_probs'], torch.tensor([-0.1, -0.2, 0.0, 0.0])), out['rollout_log_probs']
assert torch.allclose(out['token_rewards'], torch.tensor([0.0, 0.0, 0.0, 1.25])), out['token_rewards']
""",
        },
        {
            "name": "An exact fit is neither truncated nor penalized",
            "behavior": "edge.empty_or_boundary",
            "code": r"""
import torch
out = {fn}(
    torch.tensor([1, 2, 3]),
    torch.tensor([True, False, True]),
    torch.tensor([-0.2, 0.0, -0.4]),
    reward=1.5,
    max_response_length=3,
    overlong_penalty=9.0,
)
assert out['truncated'] is False
assert torch.equal(out['response_ids'], torch.tensor([1, 2, 3]))
assert torch.allclose(out['token_rewards'], torch.tensor([0.0, 0.0, 1.5])), out['token_rewards']
""",
        },
        {
            "name": "Every per-token field uses the identical prefix boundary",
            "visibility": "unshown",
            "behavior": "state.invariant",
            "failure_message": "Token ids, response_mask and rollout_log_probs were not cut at the identical prefix boundary.",
            "code": r"""
import torch
ids = torch.tensor([101, 102, 103, 104, 105, 106])
mask = torch.tensor([True, False, False, True, False, True])
log_probs = torch.tensor([-1.01, 0.0, 0.0, -1.04, 0.0, -1.06])
out = {fn}(ids, mask, log_probs, 0.0, 4, 0.0)
assert out['response_ids'].tolist() == [101, 102, 103, 104]
assert out['response_mask'].tolist() == [True, False, False, True]
assert torch.allclose(out['rollout_log_probs'], torch.tensor([-1.01, 0.0, 0.0, -1.04]))
""",
        },
        {
            "name": "Terminal reward stays on the final response position",
            "visibility": "unshown",
            "behavior": "rl.reward_verifiable",
            "failure_message": "Trajectory reward was moved to the last policy token. Store it at the final retained response position; response_mask controls gradient later.",
            "code": r"""
import torch
out = {fn}(
    torch.tensor([7, 8, 90, 91, 92]),
    torch.tensor([True, True, False, False, False]),
    torch.tensor([-0.7, -0.8, 0.0, 0.0, 0.0]),
    3.0,
    4,
    0.5,
)
assert out['truncated'] is True
assert torch.allclose(out['token_rewards'], torch.tensor([0.0, 0.0, 0.0, 2.5])), out['token_rewards']
assert out['response_mask'][-1].item() is False
""",
        },
        {
            "name": "The length penalty applies only to genuine overflow",
            "visibility": "unshown",
            "behavior": "budget.enforcement",
            "failure_message": "The overlong penalty had the wrong sign or was applied to a trajectory that fit within the limit.",
            "code": r"""
import torch
ids = torch.tensor([1, 2, 3, 4])
mask = torch.tensor([True, False, True, False])
logs = torch.tensor([-0.1, 0.0, -0.2, 0.0])
fit = {fn}(ids, mask, logs, reward=-1.0, max_response_length=5, overlong_penalty=2.5)
over = {fn}(ids, mask, logs, reward=-1.0, max_response_length=3, overlong_penalty=2.5)
assert fit['truncated'] is False and float(fit['token_rewards'].sum()) == -1.0
assert over['truncated'] is True and float(over['token_rewards'].sum()) == -3.5
""",
        },
        {
            "name": "Returned tensors do not alias caller storage",
            "visibility": "unshown",
            "behavior": "state.invariant",
            "failure_message": "A returned tensor is a view into caller-owned storage. Clone every retained tensor before returning it.",
            "code": r"""
import torch
ids = torch.tensor([1, 2, 3, 4])
mask = torch.tensor([True, False, True, False])
logs = torch.tensor([-0.1, 0.0, -0.2, 0.0])
out = {fn}(ids, mask, logs, 1.0, 3, 0.25)
out['response_ids'][0] = 99
out['response_mask'][0] = False
out['rollout_log_probs'][0] = -9.0
assert ids.tolist() == [1, 2, 3, 4], ids
assert mask.tolist() == [True, False, True, False], mask
assert torch.allclose(logs, torch.tensor([-0.1, 0.0, -0.2, 0.0])), logs
""",
        },
        {
            "name": "Preserves tensor dtypes and device",
            "visibility": "unshown",
            "behavior": "tensor.dtype_device",
            "failure_message": "The retained tensors or token rewards changed dtype or device.",
            "code": r"""
import torch
ids = torch.tensor([1, 2, 3], dtype=torch.int32)
mask = torch.tensor([True, False, True], dtype=torch.bool)
logs = torch.tensor([-0.1, 0.0, -0.2], dtype=torch.float64)
out = {fn}(ids, mask, logs, 0.5, 2, 0.1)
assert out['response_ids'].dtype == torch.int32
assert out['response_mask'].dtype == torch.bool
assert out['rollout_log_probs'].dtype == torch.float64
assert out['token_rewards'].dtype == torch.float64
for key in ('response_ids', 'response_mask', 'rollout_log_probs', 'token_rewards'):
    assert out[key].device == ids.device, (key, out[key].device, ids.device)
""",
        },
        {
            "name": "Rejects tensors that cannot stay positionally aligned",
            "visibility": "unshown",
            "behavior": "contract.signature",
            "failure_message": "Accepted tensors with mismatched lengths, ranks, dtypes or devices. The three response fields must describe the same one-dimensional positions.",
            "code": r"""
import torch
valid_ids = torch.tensor([1, 2, 3])
valid_mask = torch.tensor([True, False, True])
valid_logs = torch.tensor([-0.1, 0.0, -0.2])
bad_cases = [
    (torch.tensor([1, 2]), valid_mask, valid_logs),
    (valid_ids, torch.tensor([True, False]), valid_logs),
    (valid_ids, valid_mask, torch.tensor([-0.1, 0.0])),
    (valid_ids.reshape(1, 3), valid_mask, valid_logs),
    (valid_ids.float(), valid_mask, valid_logs),
    (valid_ids, valid_mask.long(), valid_logs),
    (valid_ids, valid_mask, valid_logs.long()),
]
for ids, mask, logs in bad_cases:
    try:
        {fn}(ids, mask, logs, 1.0, 2, 0.5)
    except ValueError:
        continue
    raise AssertionError(f'accepted ids={ids.shape}/{ids.dtype}, mask={mask.shape}/{mask.dtype}, logs={logs.shape}/{logs.dtype}')
""",
        },
        {
            "name": "Rejects empty trajectories and invalid scalar controls",
            "visibility": "unshown",
            "behavior": "edge.empty_or_boundary",
            "failure_message": "Accepted an empty trajectory, non-positive response window or negative penalty.",
            "code": r"""
import torch
empty_i = torch.tensor([], dtype=torch.long)
empty_b = torch.tensor([], dtype=torch.bool)
empty_f = torch.tensor([], dtype=torch.float32)
cases = [
    (empty_i, empty_b, empty_f, 1, 0.0),
    (torch.tensor([1]), torch.tensor([True]), torch.tensor([-0.1]), 0, 0.0),
    (torch.tensor([1]), torch.tensor([True]), torch.tensor([-0.1]), -2, 0.0),
    (torch.tensor([1]), torch.tensor([True]), torch.tensor([-0.1]), 1, -0.1),
]
for ids, mask, logs, limit, penalty in cases:
    try:
        {fn}(ids, mask, logs, 1.0, limit, penalty)
    except ValueError:
        continue
    raise AssertionError(f'accepted length={ids.numel()}, limit={limit}, penalty={penalty}')
""",
        },
    ],
    "solution": '''def finalize_agent_rollout(response_ids, response_mask, rollout_log_probs, reward, max_response_length, overlong_penalty):
    import torch

    tensors = (response_ids, response_mask, rollout_log_probs)
    if any(not isinstance(tensor, torch.Tensor) or tensor.ndim != 1 for tensor in tensors):
        raise ValueError("response tensors must be one-dimensional tensors")
    if response_ids.numel() == 0:
        raise ValueError("response tensors must be non-empty")
    if not (response_ids.numel() == response_mask.numel() == rollout_log_probs.numel()):
        raise ValueError("response tensors must have the same length")
    if not (response_ids.device == response_mask.device == rollout_log_probs.device):
        raise ValueError("response tensors must be on the same device")
    if response_ids.dtype.is_floating_point or response_ids.dtype == torch.bool:
        raise ValueError("response_ids must use an integer dtype")
    if response_mask.dtype != torch.bool:
        raise ValueError("response_mask must use boolean dtype")
    if not rollout_log_probs.dtype.is_floating_point:
        raise ValueError("rollout_log_probs must use a floating-point dtype")
    if not isinstance(max_response_length, int) or isinstance(max_response_length, bool) or max_response_length < 1:
        raise ValueError("max_response_length must be a positive integer")
    if float(overlong_penalty) < 0:
        raise ValueError("overlong_penalty must be non-negative")

    original_length = response_ids.numel()
    truncated = original_length > max_response_length
    kept = min(original_length, max_response_length)
    kept_ids = response_ids[:kept].clone()
    kept_mask = response_mask[:kept].clone()
    kept_log_probs = rollout_log_probs[:kept].clone()

    effective_reward = float(reward) - (float(overlong_penalty) if truncated else 0.0)
    token_rewards = torch.zeros_like(kept_log_probs)
    token_rewards[-1] = effective_reward

    return {
        "response_ids": kept_ids,
        "response_mask": kept_mask,
        "rollout_log_probs": kept_log_probs,
        "token_rewards": token_rewards,
        "truncated": truncated,
    }
''',
}
