"""Sampled-token OPD reward shaping on student rollouts."""

from ._interview import interview
from ._rl_extension import SLIME_OPD, case, paper, task

TASK = task(
    "OPD Sampled-KL Advantage", "Hard", "opd_sampled_kl_advantage",
    """Implement `opd_sampled_kl_advantage(advantages, student_logprobs, teacher_logprobs, mask, beta=1.0) -> Tensor`. All four tensors have matching `[batch,time]` shape. They refer to the *same tokens generated by the student*; teacher log-probabilities are evaluated on those tokens without sampling teacher trajectories. Return a detached, masked advantage tensor: `mask * (advantages - beta * (student_logprobs - teacher_logprobs))`. This sampled-token reverse-KL signal is reward/advantage shaping for a later policy-gradient loss, not a full-vocabulary KL loss; do not backpropagate through its values here. Reject shape mismatch, negative/nonfinite beta, or an all-zero mask with `ValueError`. Excluded positions are exactly zero.""",
    ["k3_kl_penalty", "reinforce_policy_loss"],
    ("Which model sampled the trajectory? Is the teacher asked for all vocabulary logits or only realized-token log probabilities?",
     "Form the student-minus-teacher sampled log-ratio, subtract its beta-weighted value from the incoming advantage, detach the result, then zero masked positions. The policy loss is a separate exercise."),
    [SLIME_OPD, paper("https://arxiv.org/abs/2601.18734", "Section 4.3.5: sampled-token advantage versus full-vocabulary distillation")],
    [
        case("Hand-calculated sampled advantage", """
import torch
a=torch.tensor([[2.,3.]])
s=torch.tensor([[-2.,-4.]])
t=torch.tensor([[-1.,-5.]])
assert torch.allclose({fn}(a,s,t,torch.tensor([[1,0]]),0.5),torch.tensor([[2.5,0.]]))
""", "rl.advantage"),
        case("Seeded independent oracle and stop gradient", """
import torch, random
random.seed(67)
torch.manual_seed(67)
for shape in [(2,4),(3,5)]:
    a=torch.randn(shape,requires_grad=True); s=torch.randn(shape,requires_grad=True); t=torch.randn(shape,requires_grad=True)
    mask=torch.randint(0,2,shape); mask[0,0]=1
    beta=random.uniform(0.1,2)
    out={fn}(a,s,t,mask,beta)
    expected=torch.zeros(shape)
    for i in range(shape[0]):
        for j in range(shape[1]):
            if mask[i,j]: expected[i,j]=a[i,j].item()-beta*(s[i,j].item()-t[i,j].item())
    assert torch.allclose(out,expected,atol=1e-6)
    assert not out.requires_grad
""", "gradient.flow", unshown=True),
        case("Rejects zero mask and mismatched shape", """
import torch
x=torch.zeros(2,3)
for a,s,t,m,b in [(x,x,x,torch.zeros_like(x),1),(x,x,x,torch.ones(3,2),1),(x,x,x,torch.ones_like(x),-1)]:
    try: {fn}(a,s,t,m,b)
    except ValueError: pass
    else: raise AssertionError('expected ValueError')
""", "edge.empty_or_boundary", unshown=True),
        case("Nonfinite masked scores cannot leak", """
import torch
a=torch.tensor([[3.,float('nan')]])
s=torch.tensor([[-2.,-float('inf')]])
t=torch.tensor([[-1.,-float('inf')]])
out={fn}(a,s,t,torch.tensor([[1,0]]))
assert torch.isfinite(out).all() and torch.allclose(out,torch.tensor([[4.,0.]]))
""", "rl.masking", unshown=True),
    ],
    '''import math
import torch

def opd_sampled_kl_advantage(advantages, student_logprobs, teacher_logprobs, mask, beta=1.0):
    if (advantages.shape != student_logprobs.shape or advantages.shape != teacher_logprobs.shape
            or advantages.shape != mask.shape or advantages.ndim != 2 or not mask.bool().any()
            or not math.isfinite(float(beta)) or beta < 0):
        raise ValueError("invalid shape, mask, or beta")
    valid = mask.bool()
    shaped = torch.zeros_like(advantages)
    shaped[valid] = (advantages[valid] - beta * (student_logprobs[valid] - teacher_logprobs[valid])).detach()
    return shaped.detach()
''',
    model_connections=["Slime's apply_opd_kl_to_advantages subtracts sampled student-minus-teacher log probability after the base advantage estimator."],
    pros=["Only the sampled token needs a teacher score, so the signal fits an existing policy-gradient trainer."],
    cons=["A single sampled token gives a noisier teacher signal than a full-vocabulary divergence."],
    interview_questions=interview(
        concept=[
            'What is on-policy distillation, and how does it differ from teacher-forced KD?',
            'Why evaluate the teacher on student-generated tokens?',
        ],
        deep_dive=[
            'Why is student minus teacher log-prob a sampled reverse-KL estimate?',
            'Why must the shaped advantage be detached?',
            'How do masked positions stay exactly zero?',
        ],
        tradeoffs=[
            'Sampled-token reverse KL versus full-vocabulary KL: variance and compute trade-offs?',
            'How do you choose beta against the task reward?',
        ],
    ),
)
